### PR TITLE
Fix typo in demo.R

### PR DESCRIPTION
**Pull request by andrey-legayev**
Fixed typo in demo/demo.R (githut->github)

### CODE REVIEW

**Comment by gufengzhou** [comment]
Sorry we neither accept nor encourage sending pull request just for changing one word in readme.

**Comment by andrey-legayev** [comment]
so, what is the way to fix it?

**Comment by gufengzhou** [comment]
We'll note this and fix it next time. Please understand that this is to avoid spam PR. This is one famous example https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama

We appreciate if you want to help us improving our project. However the changes should be substantial.

**Comment by andrey-legayev** [comment]
Ok, got it. I want to help :)
Actually I'm thinking how to speed up Robyn MMM on Win machines.

**Comment by gufengzhou** [comment]
Thanks for understanding. Feel free to raise an issue here or post it in our FB group if you want to discuss something. Looking forward to your improvement.

**Pull request closed without merging**
